#pragma config(Motor,  port1,           mL1,           tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           mL2,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           mR1,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           mR2,           tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (true) {
		
	}

}
