#pragma config(Sensor, in1,    ejctPot,        sensorPotentiometer)
#pragma config(Motor,  port1,           mEject,        tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           mL1,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           mL2,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           mR1,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           mR2,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           mClawExtend,   tmotorNone, openLoop)
#pragma config(Motor,  port6,           sClaw,         tmotorNone, openLoop)
#pragma config(Motor,  port8,           mScissor,      tmotorNone, openLoop)
#pragma config(Motor,  port9,           mTray,         tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
Eject Pot Rest: 2200
Eject Pot Ejected: 1400
Eject Motor Eject: (-)


*/
int ejectRest = 2200;
int ejectOut = 1000;

task trayCtrl {
	while(true){
		if(vexRT[Btn7U ]){
			startMotor(mEject, -100);
			while(SensorValue(ejctPot) >= ejectOut){
				wait1Msec(1);
			}
			startMotor(mEject, 100);
			while(SensorValue(ejctPot) <= ejectRest){
				wait1Msec(1);
			}
			stopMotor(mEject);
		}
	}
}
task clawCtrl {

}

float theta = 90, power = 0, x = 0, y = 0;
task main()
{
	startTask(trayCtrl);
	while (true) {
		x = vexRT[Ch3];
		y = vexRT[Ch4];
		power = sqrt(x * x + y * y);
		
		if (y > 0) {
			motor[mL1] = motor[mL2] = (y - x) / 2;
			if (x > -20 && x < 20) {
				motor[mL1] = motor[mR1] = motor[mL2] = motor[mR2] = 127;
			} else {
				motor[mL1] = motor[mR1] = (y - x) / 2;
				if (x < 0) {
					motor[mL2] = -x;
				} else {
					motor[mR2] = x;
				}
			}
		}

 		EndTimeSlice();
	}

}
