#pragma config(Sensor, in1,    potTray,        sensorPotentiometer)
#pragma config(Sensor, in2,    ejctPot,        sensorPotentiometer)
#pragma config(Sensor, in3,    potScissorL,    sensorPotentiometer)
#pragma config(Sensor, in4,    potScissorR,    sensorPotentiometer)
#pragma config(Sensor, in5,    lfClaw,         sensorLineFollower)
#pragma config(Sensor, dgtl1,  ledR,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl2,  ledG,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl3,  legB,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl4,  ,               sensorTouch)
#pragma config(Sensor, dgtl5,  ,               sensorTouch)
#pragma config(Sensor, dgtl6,  armSwitch2,     sensorTouch)
#pragma config(Sensor, dgtl7,  startAuto,      sensorTouch)
#pragma config(Sensor, dgtl8,  rEncoder,       sensorQuadEncoder)
#pragma config(Sensor, dgtl10, lEncoder,       sensorQuadEncoder)
#pragma config(Sensor, dgtl12, dgt112,         sensorTouch)
#pragma config(Motor,  port1,           mL2,           tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           mL1,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           mR1,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           mEject,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           mScissorL,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           mClaw,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           mClawExtend,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           mScissorR,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           mTray,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          mR2,           tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int ejectRest = 2200;
int ejectOut = 1000;
//----------------Auton Movement Functions-------------
void moveStraightForRotations(float rotations = 1.0)
{
	SensorValue[rEncoder] = 0;
	SensorValue[lEncoder] = 0;

	while(-SensorValue[rEncoder] < (abs(rotations) * 360))
	{
			motor[mL1] = motor[mL2] = 127;		// Left Motor is run at power level 85
			motor[mR1] = motor[mR2] = 100;		// Right Motor is run at power level 85
		wait1Msec(1);
	}
	motor[mR1] = motor[mR2] = 0;
	motor[mL1] = motor[mL2] = 0;
}
void moveBackwardForRotations(float rotations = 1.0)
{
	SensorValue[rEncoder] = 0;
	SensorValue[lEncoder] = 0;

	while(SensorValue[rEncoder] < (abs(rotations) * 360))
	{
			motor[mL1] = motor[mL2] = -127;		// Left Motor is run at power level 85
			motor[mR1] = motor[mR2] = -127;		// Right Motor is run at power level 85
		wait1Msec(1);
	}
	motor[mR1] = motor[mR2] = 0;
	motor[mL1] = motor[mL2] = 0;
}
void WideTurn(bool isRight = true, float rotations) {
	SensorValue[rEncoder] = 0;
	SensorValue[lEncoder] = 0;
	if(isRight){
		while(abs(SensorValue[lEncoder]) < abs(rotations)*360) {
			motor[mL1] = motor[mL2] = 127;
			wait1Msec(1);
		}
	} else {
		while(abs(SensorValue[lEncoder]) < abs(rotations)*360) {
			motor[mR1] = motor[mR2] = 127;
			wait1Msec(1);
		}
	}
}

void Turn(bool isRight = true, float rotations){
	SensorValue[rEncoder] = 0;
	SensorValue[lEncoder] = 0;
	if(isRight){
		while(SensorValue[lEncoder] < (abs(rotations) * 360))
		{
			motor[mR1] = motor[mR2] = -127;		// Right Motor is run at power level 85
			motor[mL1] = motor[mL2]  = 127;		// Left Motor is run at power level 85
			wait1Msec(1);
		}
	}
	else {
		while(SensorValue[rEncoder] < (abs(rotations) * 360))
		{
			motor[mR1] = motor[mR2] = 127;		// Right Motor is run at power level 85
			motor[mL1] = motor[mL2]  = -127;		// Left Motor is run at power level 85
			wait1Msec(1);
		}
	}
	motor[mR1] = motor[mR2] = 0;
	motor[mL1] = motor[mL2] = 0;
}


void trayEject () {
	motor[mEject] = -127;
	while (SensorValue(ejctPot) > ejectOut) {
		wait1Msec (1);
	}
	motor[mEject] = 127;
	while (SensorValue(ejctPot) < ejectRest) {
		wait1Msec (1);
	}
	motor[mEject] = 0;
}

void liftTray () {
	motor[mTray] = -127;
	wait1Msec (1500);
	motor[mTray] = -20;
}

const float angle90l = 0.28, angle90r = 0.55;
const float angle180l = 0.69, angle180r = 1.15;
const float _distanceGrabGoal = 4.8;

void autoRight5 () {
	motor[mClawExtend] = 127;
	wait1Msec (2500);
	motor[mClawExtend] = 0;
	SensorValue[rEncoder] = 0;
	SensorValue[lEncoder] = 0;
	moveStraightForRotations (_distanceGrabGoal);
	motor[mR1] = motor[mR2] = 0;
	motor[mL1] = motor[mL2] = 0;
	motor[mTray] = -127;
	wait1Msec (1600);
	motor[mTray] = -20;
	moveBackwardForRotations (2.0);
	wait1Msec (500);
	Turn(false, 0.99);
	wait1Msec(500);
	moveStraightForRotations (0.9);
	trayEject ();
	motor[mL1] = motor[mL2] = -127;
	motor[mR1] = motor[mR2] = -127;
	wait1Msec(800);
}

void autoRight20 () {
	motor[mClawExtend] = 127;
	wait1Msec (2500);
	motor[mClawExtend] = 0;
	moveStraightForRotations (_distanceGrabGoal);
	motor[mTray] = -127;
	wait1Msec (1600);
	motor[mTray] = -20;
	moveBackwardForRotations (2.0);
	wait1Msec (500);
	Turn(false, 0.97);
	wait1Msec(500);
	moveStraightForRotations (2.1);
	motor[mR1] = motor[mR2] = 127;
	wait1Msec (1200);
	motor[mL1] = motor[mL2] = -127;
	motor[mR1] = motor[mR2] = -127;
	wait1Msec(600);
	motor[mL1] = motor[mL2] = 0;
	motor[mR1] = motor[mR2] = 0;
wait1Msec (500);
	motor[mL1] = motor[mL2] = 127;
	motor[mR1] = motor[mR2] = 127;
	wait1Msec (3000);
	motor[mL1] = motor[mL2] = 0;
	motor[mR1] = motor[mR2] = 0;
	trayEject ();
	motor[mL1] = motor[mL2] = -127;
	motor[mR1] = motor[mR2] = -127;
	wait1Msec(1300);
}

void autoLeft20 () {
	motor[mClawExtend] = 127;
	wait1Msec (2500);
	motor[mClawExtend] = 0;
	SensorValue[rEncoder] = 0;
	SensorValue[lEncoder] = 0;
	while(-SensorValue[rEncoder] < (abs(_distanceGrabGoal) * 360))
	{
		motor[mL1] = motor[mL2] = 127;		// Left Motor is run at power level 85
		motor[mR1] = motor[mR2] = 120;		// Right Motor is run at power level 85
		wait1Msec(1);
	}
	motor[mR1] = motor[mR2] = 0;
	motor[mL1] = motor[mL2] = 0;
	motor[mTray] = -127;
	wait1Msec (1600);
	motor[mTray] = -20;
	moveBackwardForRotations (2.0);
	wait1Msec (500);
	Turn(false, 0.99);
	wait1Msec(500);
	moveStraightForRotations (2.1);
	motor[mL1] = motor[mL2] = 127;
	wait1Msec (1200);
	motor[mL1] = motor[mL2] = -127;
	motor[mR1] = motor[mR2] = -127;
	wait1Msec(600);
	motor[mL1] = motor[mL2] = 0;
	motor[mR1] = motor[mR2] = 0;
wait1Msec (500);
	motor[mL1] = motor[mL2] = 127;
	motor[mR1] = motor[mR2] = 127;
	wait1Msec (3000);
	motor[mL1] = motor[mL2] = 0;
	motor[mR1] = motor[mR2] = 0;
	trayEject ();
	motor[mL1] = motor[mL2] = -127;
	motor[mR1] = motor[mR2] = -127;
	wait1Msec(1300);
}

void autoLeft5 () {
	motor[mClawExtend] = 127;
	wait1Msec (2500);
	motor[mClawExtend] = 0;
	SensorValue[rEncoder] = 0;
	SensorValue[lEncoder] = 0;
	while(-SensorValue[rEncoder] < (abs(_distanceGrabGoal) * 360))
	{
		motor[mL1] = motor[mL2] = 127;		// Left Motor is run at power level 85
		motor[mR1] = motor[mR2] = 120;		// Right Motor is run at power level 85
		wait1Msec(1);
	}
	motor[mR1] = motor[mR2] = 0;
	motor[mL1] = motor[mL2] = 0;
	motor[mTray] = -127;
	wait1Msec (1600);
	motor[mTray] = -20;
	moveBackwardForRotations (2.0);
	wait1Msec (500);
	Turn(true, 1.02);
	wait1Msec(500);
	moveStraightForRotations (0.9);
	trayEject ();

	motor[mL1] = motor[mL2] = -127;
	motor[mR1] = motor[mR2] = -127;
	wait1Msec(800);
}

void defendLeft () {
	moveStraightForRotations (1.7);
	Turn (true, 0.18);
	SensorValue[rEncoder] = 0;
	SensorValue[lEncoder] = 0;
	while(-SensorValue[rEncoder] < (abs(6.5) * 360))
	{
		motor[mL1] = motor[mL2] = 127;		// Left Motor is run at power level 85
		motor[mR1] = motor[mR2] = 127;		// Right Motor is run at power level 85
		wait1Msec(1);
	}
	motor[mR1] = motor[mR2] = 0;
	motor[mL1] = motor[mL2] = 0;
}

void defendRight () {
	moveStraightForRotations (1.2);
	Turn (false, 0.20);
	SensorValue[rEncoder] = 0;
	SensorValue[lEncoder] = 0;
	while(-SensorValue[rEncoder] < (abs(6.5) * 360))
	{
		motor[mL1] = motor[mL2] = 127;		// Left Motor is run at power level 85
		motor[mR1] = motor[mR2] = 127;		// Right Motor is run at power level 85
		wait1Msec(1);
	}
	motor[mR1] = motor[mR2] = 0;
	motor[mL1] = motor[mL2] = 0;
}

task main()
{
	//liftTray ();
	//moveStraightForRotations (1);
	//Turn(false, angle180l);
	//autoLeft5 ();
autoRight5 ();
motor[mL1] = motor[mL2] = 0;
	motor[mR1] = motor[mR2] = 0;
	//moveStraightForRotations (_distanceGrabGoal);
	/*
	wait1Msec (500);
	Turn (true, angle90r);
	wait1Msec (500);
	Turn (false, angle90l);
	wait1Msec (500);
	Turn (false, angle180l);
	wait1Msec (500);
	Turn (true, angle180r);
	//moveBackwardForRotations (1.0);
	*/
}
