#pragma config(Sensor, in1,    potTray,        sensorPotentiometer)
#pragma config(Sensor, in2,    ejctPot,        sensorPotentiometer)
#pragma config(Sensor, in3,    potScissorL,    sensorPotentiometer)
#pragma config(Sensor, in4,    potScissorR,    sensorPotentiometer)
#pragma config(Sensor, in5,    lfClaw,         sensorLineFollower)
#pragma config(Sensor, dgtl1,  autoDirectionLeft, sensorTouch)
#pragma config(Sensor, dgtl2,  autoScore20Points, sensorTouch)
#pragma config(Sensor, dgtl3,  autoPlayDefend, sensorTouch)
#pragma config(Sensor, dgtl4,  ,               sensorTouch)
#pragma config(Sensor, dgtl5,  ,               sensorTouch)
#pragma config(Sensor, dgtl6,  armSwitch2,     sensorTouch)
#pragma config(Sensor, dgtl7,  startAuto,      sensorTouch)
#pragma config(Sensor, dgtl8,  rEncoder,       sensorQuadEncoder)
#pragma config(Sensor, dgtl10, lEncoder,       sensorQuadEncoder)
#pragma config(Sensor, dgtl12, antiGravity,    sensorTouch)
#pragma config(Motor,  port1,           mL2,           tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           mL1,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           mR1,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           mEject,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           mScissorL,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           mClaw,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           mClawExtend,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           mScissorR,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           mTray,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          mR2,           tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"


#define potScissorErrorAllowance 50
#define TURNING_COEFFICIENT 0.7
int antiGravityAmount = 0;

int max (int a, int b) {
	return (a > b ? a : b);
}
int min (int a, int b) {
	return (a < b ? a : b);
}

/*
Eject Pot Rest: 2200
Eject Pot Ejected: 1400
Eject Motor Eject: (-)
*/
int ejectRest = 2200;
int ejectOut = 1000;
int activationDelay = 1000;

//int stackedCount = 0;
//int potPositions[12] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
//int mScissorValues[2] = {127, -127};


int scissorLeftHeight = 0, scissorRightHeight = 0;

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

void moveStraightForRotations(float rotations = 1.0)
{
	SensorValue[rEncoder] = 0;
	SensorValue[lEncoder] = 0;

	while(-SensorValue[rEncoder] < (abs(rotations) * 360))
	{
			motor[mL1] = motor[mL2] = 127;		// Left Motor is run at power level 85
			motor[mR1] = motor[mR2] = 100;		// Right Motor is run at power level 85
		wait1Msec(1);
	}
	motor[mR1] = motor[mR2] = 0;
	motor[mL1] = motor[mL2] = 0;
}
void moveBackwardForRotations(float rotations = 1.0)
{
	SensorValue[rEncoder] = 0;
	SensorValue[lEncoder] = 0;

	while(SensorValue[rEncoder] < (abs(rotations) * 360))
	{
			motor[mL1] = motor[mL2] = -127;		// Left Motor is run at power level 85
			motor[mR1] = motor[mR2] = -127;		// Right Motor is run at power level 85
		wait1Msec(1);
	}
	motor[mR1] = motor[mR2] = 0;
	motor[mL1] = motor[mL2] = 0;
}
void WideTurn(bool isRight = true, float rotations) {
	SensorValue[rEncoder] = 0;
	SensorValue[lEncoder] = 0;
	if(isRight){
		while(abs(SensorValue[lEncoder]) < abs(rotations)*360) {
			motor[mL1] = motor[mL2] = 127;
			wait1Msec(1);
		}
	} else {
		while(abs(SensorValue[lEncoder]) < abs(rotations)*360) {
			motor[mR1] = motor[mR2] = 127;
			wait1Msec(1);
		}
	}
}

void Turn(bool isRight = true, float rotations){
	SensorValue[rEncoder] = 0;
	SensorValue[lEncoder] = 0;
	if(isRight){
		while(SensorValue[lEncoder] < (abs(rotations) * 360))
		{
			motor[mR1] = motor[mR2] = -127;		// Right Motor is run at power level 85
			motor[mL1] = motor[mL2]  = 127;		// Left Motor is run at power level 85
			wait1Msec(1);
		}
	}
	else {
		while(SensorValue[rEncoder] < (abs(rotations) * 360))
		{
			motor[mR1] = motor[mR2] = 127;		// Right Motor is run at power level 85
			motor[mL1] = motor[mL2]  = -127;		// Left Motor is run at power level 85
			wait1Msec(1);
		}
	}
	motor[mR1] = motor[mR2] = 0;
	motor[mL1] = motor[mL2] = 0;
}


void trayEject () {
	motor[mEject] = -127;
	while (SensorValue(ejctPot) > ejectOut) {
		wait1Msec (1);
	}
	motor[mEject] = 127;
	while (SensorValue(ejctPot) < ejectRest) {
		wait1Msec (1);
	}
	motor[mEject] = 0;
}

void liftTray () {
	motor[mTray] = -127;
	wait1Msec (1500);
	motor[mTray] = -20;
}

const float angle90l = 0.28, angle90r = 0.55;
const float angle180l = 0.69, angle180r = 1.15;
const float _distanceGrabGoal = 4.8;

void autoRight5 () {
	motor[mClawExtend] = 127;
	wait1Msec (2500);
	motor[mClawExtend] = 0;
	SensorValue[rEncoder] = 0;
	SensorValue[lEncoder] = 0;
	moveStraightForRotations (_distanceGrabGoal);
	motor[mR1] = motor[mR2] = 0;
	motor[mL1] = motor[mL2] = 0;
	motor[mTray] = -127;
	wait1Msec (1600);
	motor[mTray] = -20;
	moveBackwardForRotations (2.0);
	wait1Msec (500);
	Turn(false, 0.99);
	wait1Msec(500);
	moveStraightForRotations (0.9);
	trayEject ();
	motor[mL1] = motor[mL2] = -127;
	motor[mR1] = motor[mR2] = -127;
	wait1Msec(800);
}

void autoRight20 () {
	motor[mClawExtend] = 127;
	wait1Msec (2500);
	motor[mClawExtend] = 0;
	moveStraightForRotations (_distanceGrabGoal);
	motor[mTray] = -127;
	wait1Msec (1600);
	motor[mTray] = -20;
	moveBackwardForRotations (2.0);
	wait1Msec (500);
	Turn(false, 0.97);
	wait1Msec(500);
	moveStraightForRotations (2.1);
	motor[mR1] = motor[mR2] = 127;
	wait1Msec (1200);
	motor[mL1] = motor[mL2] = -127;
	motor[mR1] = motor[mR2] = -127;
	wait1Msec(600);
	motor[mL1] = motor[mL2] = 0;
	motor[mR1] = motor[mR2] = 0;
wait1Msec (500);
	motor[mL1] = motor[mL2] = 127;
	motor[mR1] = motor[mR2] = 127;
	wait1Msec (3000);
	motor[mL1] = motor[mL2] = 0;
	motor[mR1] = motor[mR2] = 0;
	trayEject ();
	motor[mL1] = motor[mL2] = -127;
	motor[mR1] = motor[mR2] = -127;
	wait1Msec(1300);
}

void autoLeft20 () {
	motor[mClawExtend] = 127;
	wait1Msec (2500);
	motor[mClawExtend] = 0;
	SensorValue[rEncoder] = 0;
	SensorValue[lEncoder] = 0;
	while(-SensorValue[rEncoder] < (abs(_distanceGrabGoal) * 360))
	{
		motor[mL1] = motor[mL2] = 127;		// Left Motor is run at power level 85
		motor[mR1] = motor[mR2] = 120;		// Right Motor is run at power level 85
		wait1Msec(1);
	}
	motor[mR1] = motor[mR2] = 0;
	motor[mL1] = motor[mL2] = 0;
	motor[mTray] = -127;
	wait1Msec (1600);
	motor[mTray] = -20;
	moveBackwardForRotations (2.0);
	wait1Msec (500);
	Turn(false, 0.99);
	wait1Msec(500);
	moveStraightForRotations (2.1);
	motor[mL1] = motor[mL2] = 127;
	wait1Msec (1200);
	motor[mL1] = motor[mL2] = -127;
	motor[mR1] = motor[mR2] = -127;
	wait1Msec(600);
	motor[mL1] = motor[mL2] = 0;
	motor[mR1] = motor[mR2] = 0;
wait1Msec (500);
	motor[mL1] = motor[mL2] = 127;
	motor[mR1] = motor[mR2] = 127;
	wait1Msec (3000);
	motor[mL1] = motor[mL2] = 0;
	motor[mR1] = motor[mR2] = 0;
	trayEject ();
	motor[mL1] = motor[mL2] = -127;
	motor[mR1] = motor[mR2] = -127;
	wait1Msec(1300);
}

void autoLeft5 () {
	motor[mClawExtend] = 127;
	wait1Msec (2500);
	motor[mClawExtend] = 0;
	SensorValue[rEncoder] = 0;
	SensorValue[lEncoder] = 0;
	while(-SensorValue[rEncoder] < (abs(_distanceGrabGoal) * 360))
	{
		motor[mL1] = motor[mL2] = 127;		// Left Motor is run at power level 85
		motor[mR1] = motor[mR2] = 120;		// Right Motor is run at power level 85
		wait1Msec(1);
	}
	motor[mR1] = motor[mR2] = 0;
	motor[mL1] = motor[mL2] = 0;
	motor[mTray] = -127;
	wait1Msec (1600);
	motor[mTray] = -20;
	moveBackwardForRotations (2.0);
	wait1Msec (500);
	Turn(true, 1.02);
	wait1Msec(500);
	moveStraightForRotations (0.9);
	trayEject ();

	motor[mL1] = motor[mL2] = -127;
	motor[mR1] = motor[mR2] = -127;
	wait1Msec(800);
}

void defendLeft () {
	moveStraightForRotations (1.7);
	Turn (true, 0.18);
	SensorValue[rEncoder] = 0;
	SensorValue[lEncoder] = 0;
	while(-SensorValue[rEncoder] < (abs(6.5) * 360))
	{
		motor[mL1] = motor[mL2] = 127;		// Left Motor is run at power level 85
		motor[mR1] = motor[mR2] = 127;		// Right Motor is run at power level 85
		wait1Msec(1);
	}
	motor[mR1] = motor[mR2] = 0;
	motor[mL1] = motor[mL2] = 0;
}

void defendRight () {
	moveStraightForRotations (1.2);
	Turn (false, 0.20);
	SensorValue[rEncoder] = 0;
	SensorValue[lEncoder] = 0;
	while(-SensorValue[rEncoder] < (abs(6.5) * 360))
	{
		motor[mL1] = motor[mL2] = 127;		// Left Motor is run at power level 85
		motor[mR1] = motor[mR2] = 127;		// Right Motor is run at power level 85
		wait1Msec(1);
	}
	motor[mR1] = motor[mR2] = 0;
	motor[mL1] = motor[mL2] = 0;
}
task autonomous()
{
	if (SensorValue(autoPlayDefend)) {
		if (SensorValue(autoDirectionLeft)) {
			defendLeft ();
		} else {
			defendRight ();
		}
	} else {
		if (SensorValue(autoScore20Points)) {
			if (SensorValue(autoDirectionLeft)) {
				autoLeft20 ();
			} else {
				autoRight20 ();
			}
		} else {
			if (SensorValue(autoDirectionLeft)) {
				autoLeft5 ();
			} else {
				autoRight5 ();
			}
		}
	}
	motor[mR1] = motor[mR2] = 0;
	motor[mL1] = motor[mL2] = 0;
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/



task trayCtrl {
	int ejectFlag;
	while (true) {
		if (vexRT[Btn7L]){
			ejectFlag = 0;
			motor[mEject] = -127;
			while (SensorValue(ejctPot) > ejectOut) {
				if (ejectFlag == 0 && vexRT[Btn7L]) {
					ejectFlag = 1;
				} else if (ejectFlag == 1 && !vexRt[Btn7L]) {
					ejectFlag = 2;
				} else if (ejectFlag == 2 && vexRT[btn7L]) {
					motor[mEject] = 0;
					wait10Msec (50);
					break;
				}
				wait1Msec (10);
			}
			motor[mEject] = 127;
			while (SensorValue(ejctPot) < ejectRest) {
				if (ejectFlag == 0 && vexRT[Btn7L]) {
					ejectFlag = 1;
				} else if (ejectFlag == 1 && !vexRt[Btn7L]) {
					ejectFlag = 2;
				} else if (ejectFlag == 2 && vexRT[btn7L]) {
					motor[mEject] = 0;
					wait10Msec (50);
					break;
				}
				wait1Msec (10);
			}
			motor[mEject] = 0;
		}

		if (vexRT[Btn8D]) {
			motor[mTray] = 127;
		} else if (vexRT[Btn8U]) {
			motor[mTray] = -127;
		} else {
			motor[mTray] = 0;
		}
/*
		if (vexRT[Btn8U]) {
			motor[mTray] = -127;
			while (SensorValue[potTray] < __POS_UP__) {
				wait1Msec (25);
				if (vexRT[Btn8L]) {
					break;
				}
			}
		} else if (vexRT[Btn8R]) {
			motor[mtray] = 127;
			while (SensorValue[potTray] > __POS_DOWN__) {
				wait1Msec (25);
				if (vexRT[Btn8L]) {
					break;
				}
			}
			motor[mTray] = 0;
		}
		*/
		wait1Msec (10);
		EndTimeSlice ();
	}
}


task scissorLiftControl {
	const int toph = 1300, bottomh = 0;
	while (true) {
		if (vexRT[Btn5U]) {
			if (scissorLeftHeight < toph && scissorRightHeight < toph &&
				abs(scissorLeftHeight - scissorRightHeight) < potScissorErrorAllowance) {
				motor[mScissorL] = motor[mScissorR] = -127;
			} else {
				motor[mScissorL] = (scissorLeftHeight < toph) * (scissorLeftHeight > scissorRightHeight ? 0 : -127);
				motor[mScissorR] = (scissorRightHeight < toph) * (scissorLeftHeight < scissorRightHeight ? 0 : -127);
			}
		} else if (vexRT[Btn5D]){
			if (scissorLeftHeight > 50 && scissorRightHeight > 50 &&
				abs(scissorLeftHeight - scissorRightHeight) < potScissorErrorAllowance) {
				motor[mScissorL] = motor[mScissorR] = 127;
			} else {
				motor[mScissorL] = (scissorLeftHeight > bottomh) * (scissorLeftHeight < scissorRightHeight ? 0 : 127);
				motor[mScissorR] = (scissorRightHeight > bottomh) * (scissorLeftHeight > scissorRightHeight ? 0 : 127);
			}
		} else {
			//if (abs(scissorLeftHeight - scissorRightHeight) < potScissorErrorAllowance) {
			//	motor[mScissorL] = (scissorLeftHeight < scissorRightHeight ? -70 : 70);
			//	motor[mScissorR] = 0;
			//} else {
				motor[mScissorL] = motor[mScissorR] = 0;
			//}
		}
	}
}

bool clawOpen = true;
bool autoStacking = false;

task manualStack{
	while (true){

		if (vexRT[Btn6U]){
			if (autoStacking) {
				autoStacking = false;
			}
			autoStacking = false;
		} else if (vexRT[Btn6D]) {
			if (autoStacking) {
				autoStacking = false;
			}
			motor[mClawExtend] = -127;
		} else if (!autoStacking) {
			motor[mClawExtend] = antiGravityAmount;
		}
	}
}

task toggleClaw {
	while (true) {
		if (vexRT[Btn8L]) {
			while (vexRT[Btn8L]) { }
			if (clawOpen) {
				motor[mClaw] = 127;
				wait1Msec (250);
				motor[mClaw] = 30;
			} else {
				motor[mClaw] = -127;
				wait1Msec (600);
			}
			clawOpen = !clawOpen;
		}
		if (!autoStacking) {
			motor[mClaw] = (clawOpen ? 0 : 30);
		}
		EndTimeSlice ();
	}
}


task usercontrol()
{
  if (SensorValue (antiGravity)) {
		antiGravityAmount = 10;
	}

	//startTask(manualCtrl);
	startTask (trayCtrl);
	startTask (scissorLiftControl);

	//startTask (autoStack);
	startTask (toggleClaw);
	startTask (manualStack);
	float theta = 90, power = 0, x = 0, y = 0, z = 0, direction = 1;
	int motorL1, motorL2, motorR1, motorR2;

	while (true) {

		// Update Sensor Values
		scissorLeftHeight = SensorValue[potScissorL] - 1400;
		scissorRightHeight = SensorValue[potScissorR] - 1100;

		motor[mL1] = motor[mL2] = vexRT[Ch3];
		motor[mR1] = motor[mR2] = vexRT[Ch2];

 		EndTimeSlice();
	}
}
