#pragma config(Sensor, in1,    ejctPot,        sensorPotentiometer)
#pragma config(Sensor, dgtl1,  ledR,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl2,  ledG,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl3,  legB,           sensorLEDtoVCC)
#pragma config(Motor,  port1,           mEject,        tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           mL1,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           mL2,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           mR1,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           mR2,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           sClaw,         tmotorServoStandard, openLoop)
#pragma config(Motor,  port7,           mClawExtend,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           mScissor,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           mTray,         tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
Eject Pot Rest: 2200
Eject Pot Ejected: 1400
Eject Motor Eject: (-)


*/
int ejectRest = 2200;
int ejectOut = 1000;

task trayCtrl {
	while(true){
		if(vexRT[Btn7U ]){
			motor[mEject] = -100;
			while(SensorValue(ejctPot) >= ejectOut){
				wait1Msec(1);
			}
			motor[mEject] = 100;
			while(SensorValue(ejctPot) <= ejectRest){
				wait1Msec(1);
			}
			motor[mEject] = 0;
		}
	}
}
task clawCtrl {
	while(true){
		if(vexRT[Btn8L]){
			setServo(sClaw, 127);
		}
		if(vexRT[Btn8R]){
			setServo(sClaw, -127);
		}
	}
}

float theta = 90, power = 0, x = 0, y = 0, direction = 1;
task main()
{
	startTask(clawCtrl);
	startTask(trayCtrl);
	while (true) {
		x = vexRT[Ch4];
		y = vexRT[Ch3];
		power = sqrt(x * x + y * y);
		if (power > 10) {
			//if (y > 0) {
			if (power > 100) {
				power = 127;
			}
			direction = (y < 0 ? -1 : 1);
				motor[mL1] = motor[mL2] = (y - x) / 2;
				if (x > -20 && x < 20) {
					motor[mL1] = motor[mR1] = motor[mL2] = motor[mR2] = direction * power;
				} else {
					if (x < 0) {
						motor[mL2] = 0;
						motor[mR2] = direction * -x * (power / 127.0);
						motor[mL1] = motor[mR1] = (1.2 * y) / 2;
					} else {
						motor[mL2] = direction * x * (power / 127.0);
						motor[mR2] = 0;
						motor[mL1] = motor[mR1] = (1.2 * y) / 2;
					}
				}
		} else {
			motor[mL1] = motor[mL2] = motor[mR1] = motor[mR2] = 0;
		}

		x = vexRT[Ch1];
		y = vexRT[Ch2];
		power = sqrt(x * x + y * y);

		if (power > 50) {
			if (x > - 25 && x < 25) {

			} else if (y > -25 && y < 25) {
				if (x < 0) {
					motor[mL1] = motor[mL2] = -power;
					motor[mR1] = motor[mR2] = power;
				} else {
					motor[mL1] = motor[mL2] = power;
					motor[mR1] = motor[mR2] = -power;
				}
			}
		}

		if (vexRT[Btn6U]) {
			motor[mTray] = -127;
		} else if (vexRT[Btn6D]) {
			motor[mTray] = 127;
		} else {
			motor[mTray] = 0;
		}

 		EndTimeSlice();
	}

}
