#pragma config(Sensor, in1,    potGoalLift,    sensorPotentiometer)
#pragma config(Sensor, in2,    ejctPot,        sensorPotentiometer)
#pragma config(Sensor, in3,    potScissorL,    sensorPotentiometer)
#pragma config(Sensor, in4,    potScissorR,    sensorPotentiometer)
#pragma config(Sensor, in5,    lfL2,           sensorLineFollower)
#pragma config(Sensor, in6,    lfR2,           sensorLineFollower)
#pragma config(Sensor, dgtl1,  ledR,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl2,  ledG,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl3,  legB,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl6,  startAuto,      sensorTouch)
#pragma config(Sensor, dgtl7,  touchClawExt,   sensorTouch)
#pragma config(Sensor, dgtl12, antiGravity,    sensorTouch)
#pragma config(Motor,  port1,           mEject,        tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           mL1,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           mL2,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           mR1,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           mScissorL,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           mClaw,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           mClawExtend,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           mScissorR,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           mTray,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          mR2,           tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define potScissorErrorAllowance 50
#define TURNING_COEFFICIENT 0.7
int antiGravityAmount = 0;

int max (int a, int b) {
	return (a > b ? a : b);
}
int min (int a, int b) {
	return (a < b ? a : b);
}

/*
Eject Pot Rest: 2200
Eject Pot Ejected: 1400
Eject Motor Eject: (-)
*/
int ejectRest = 2200;
int ejectOut = 1000;
int activationDelay = 1000;

//int stackedCount = 0;
//int potPositions[12] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
//int mScissorValues[2] = {127, -127};


int scissorLeftHeight = 0, scissorRightHeight = 0;

task trayCtrl {
	int ejectFlag;
	while (true) {
		if (vexRT[Btn7L]){
			ejectFlag = 0;
			motor[mEject] = -100;
			while (SensorValue(ejctPot) > ejectOut) {
				if (ejectFlag == 0 && vexRT[Btn7L]) {
					ejectFlag = 1;
				} else if (ejectFlag == 1 && !vexRt[Btn7L]) {
					ejectFlag = 2;
				} else if (ejectFlag == 2 && vexRT[btn7L]) {
					motor[mEject] = 0;
					wait10Msec (50);
					break;
				}
				wait1Msec (10);
			}
			motor[mEject] = 100;
			while (SensorValue(ejctPot) < ejectRest) {
				if (ejectFlag == 0 && vexRT[Btn7L]) {
					ejectFlag = 1;
				} else if (ejectFlag == 1 && !vexRt[Btn7L]) {
					ejectFlag = 2;
				} else if (ejectFlag == 2 && vexRT[btn7L]) {
					motor[mEject] = 0;
					wait10Msec (50);
					break;
				}
				wait1Msec (10);
			}
			motor[mEject] = 0;
		}

		if (vexRT[Btn8D]) {
			motor[mTray] = 127;
		} else if (vexRT[Btn8U]) {
			motor[mTray] = -127;
		} else {
			motor[mTray] = 0;
		}
/*
		if (vexRT[Btn8U]) {
			motor[mTray] = -127;
			while (SensorValue[potTray] < __POS_UP__) {
				wait1Msec (25);
				if (vexRT[Btn8L]) {
					break;
				}
			}
		} else if (vexRT[Btn8R]) {
			motor[mtray] = 127;
			while (SensorValue[potTray] > __POS_DOWN__) {
				wait1Msec (25);
				if (vexRT[Btn8L]) {
					break;
				}
			}
			motor[mTray] = 0;
		}
		*/
		wait1Msec (10);
		EndTimeSlice ();
	}
}


task scissorLiftControl {
	const int toph = 1300, bottomh = 0;
	while (true) {
		if (vexRT[Btn5U]) {
			if (scissorLeftHeight < toph && scissorRightHeight < toph &&
				abs(scissorLeftHeight - scissorRightHeight) < potScissorErrorAllowance) {
				motor[mScissorL] = motor[mScissorR] = -127;
			} else {
				motor[mScissorL] = (scissorLeftHeight < toph) * (scissorLeftHeight > scissorRightHeight ? 0 : -127);
				motor[mScissorR] = (scissorRightHeight < toph) * (scissorLeftHeight < scissorRightHeight ? 0 : -127);
			}
		} else if (vexRT[Btn5D]){
			if (scissorLeftHeight > 50 && scissorRightHeight > 50 &&
				abs(scissorLeftHeight - scissorRightHeight) < potScissorErrorAllowance) {
				motor[mScissorL] = motor[mScissorR] = 127;
			} else {
				motor[mScissorL] = (scissorLeftHeight > bottomh) * (scissorLeftHeight < scissorRightHeight ? 0 : 127);
				motor[mScissorR] = (scissorRightHeight > bottomh) * (scissorLeftHeight > scissorRightHeight ? 0 : 127);
			}
		} else {
			//if (abs(scissorLeftHeight - scissorRightHeight) < potScissorErrorAllowance) {
			//	motor[mScissorL] = (scissorLeftHeight < scissorRightHeight ? -70 : 70);
			//	motor[mScissorR] = 0;
			//} else {
				motor[mScissorL] = motor[mScissorR] = 0;
			//}
		}
	}
}

bool clawOpen = true;
bool autoStacking = false;
task autoStack {
	while (true) {
		if (vexRT[Btn7R] && !autoStacking) {
			if (autoStacking) {
				break;
			}
			autoStacking = true;
			motor[mClawExtend] = 127;
			//wait1Msec(1500);
			while (!SensorValue[touchClawExt]) {
				wait1Msec (5);
			}
			//wait1Msec (10);
			//motor[mClaw] = -127;
			motor[mClawExtend] = -10;
			wait1Msec (400);
			motor[mClaw] = -127;
			wait1Msec (300);
			motor[mClaw] = 0;
			clawOpen = true;
			wait1Msec (1000);
			motor[mClawExtend] = -127;
			wait1Msec (1000);
			motor[mClawExtend] = 0;
			autoStacking = false;
			//while (abs(SensorValue[potScissor] - potPositions[stackedCount]) > potScissorErrorAllowance) {
				//motor[mScissorL] = mScissorValues[SensorValue[potScissor] < potPositions[stackedCount]];
			//}
		}

				EndTimeSlice();
	}
}
task manualStack{
	while (true){

		if (vexRT[Btn6U]){
			if (autoStacking) {
				stopTask (autoStack);
				startTask (autoStack);
				autoStacking = false;
			}
			autoStacking = false;
			if (vexRT[touchClawExt]) {
				motor[mClawExtend] = -10;
			} else {
				motor[mClawExtend] = 127;
			}
		} else if (vexRT[Btn6D]) {
			if (autoStacking) {
				stopTask (autoStack);
				startTask (autoStack);
				autoStacking = false;
			}
			motor[mClawExtend] = -127;
		} else if (!autoStacking) {
			motor[mClawExtend] = antiGravityAmount;
		}
	}
}

task toggleClaw {
	while (true) {
		if (vexRT[Btn8L]) {
			while (vexRT[Btn8L]) { }
			if (clawOpen) {
				motor[mClaw] = 127;
				wait1Msec (250);
				motor[mClaw] = 30;
			} else {
				motor[mClaw] = -127;
				wait1Msec (600);
			}
			clawOpen = !clawOpen;
		}
		if (!autoStacking) {
			motor[mClaw] = (clawOpen ? 0 : 30);
		}
		EndTimeSlice ();
	}
}

task main()
{
	if (SensorValue (antiGravity)) {
		antiGravityAmount = 10;
	}

	//startTask(manualCtrl);
	startTask (trayCtrl);
	startTask (scissorLiftControl);


	startTask (autoStack);
	startTask (toggleClaw);
	startTask (manualStack);
	float theta = 90, power = 0, x = 0, y = 0, z = 0, direction = 1;
	int motorL1, motorL2, motorR1, motorR2;

	while (true) {

		// Update Sensor Values
		scissorLeftHeight = SensorValue[potScissorL] - 1400;
		scissorRightHeight = SensorValue[potScissorR] - 1100;

		motor[mL1] = motor[mL2] = vexRT[Ch3];
		motor[mR1] = motor[mR2] = vexRT[Ch2];




 		EndTimeSlice();
	}

}
