#pragma config(Sensor, in1,    potGoalLift,    sensorPotentiometer)
#pragma config(Sensor, in2,    ejctPot,        sensorPotentiometer)
#pragma config(Sensor, in3,    potScissorL,    sensorPotentiometer)
#pragma config(Sensor, in4,    potScissorR,    sensorPotentiometer)
#pragma config(Sensor, in5,    lfClaw,         sensorLineFollower)
#pragma config(Sensor, dgtl1,  ledR,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl2,  ledG,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl3,  legB,           sensorLEDtoVCC)
#pragma config(Motor,  port1,           mEject,        tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           mL1,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           mL2,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           mR1,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           mScissorL,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           mClaw,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           mClawExtend,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           mScissorR,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           mTray,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          mR2,           tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define potScissorErrorAllowance 50
#define TURNING_COEFFICIENT 0.7

int max (int a, int b) {
	return (a > b ?  a : b);
}

/*
Eject Pot Rest: 2200
Eject Pot Ejected: 1400
Eject Motor Eject: (-)
*/
int ejectRest = 2200;
int ejectOut = 1000;
int activationDelay = 1000;

//int stackedCount = 0;
//int potPositions[12] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
//int mScissorValues[2] = {127, -127};


int scissorLeftHeight = 0, scissorRightHeight = 0;

task trayCtrl {
	while (true) {
		if (vexRT[Btn7U]){
			motor[mEject] = -100;
			while (SensorValue(ejctPot) > ejectOut) {
				wait1Msec (10);
			}
			motor[mEject] = 100;
			while (SensorValue(ejctPot) < ejectRest) {
				wait1Msec (10);
			}
			motor[mEject] = 0;
		}

		if (vexRT[Btn8D]) {
			motor[mTray] = 127;
		} else if (vexRT[Btn8U]) {
			motor[mTray] = -127;
		} else {
			motor[mTray] = 0;
		}
/*
		if (vexRT[Btn8U]) {
			motor[mTray] = -127;
			while (SensorValue[potTray] < __POS_UP__) {
				wait1Msec (25);
				if (vexRT[Btn8L]) {
					break;
				}
			}
		} else if (vexRT[Btn8R]) {
			motor[mtray] = 127;
			while (SensorValue[potTray] > __POS_DOWN__) {
				wait1Msec (25);
				if (vexRT[Btn8L]) {
					break;
				}
			}
			motor[mTray] = 0;
		}
		*/
		wait1Msec (10);
		EndTimeSlice ();
	}
}

task scissorLiftControl {
	while (true) {
		if (vexRT[Btn5U]) {
			if (scissorLeftHeight - potScissorErrorAllowance > scissorRightHeight) {
				motor[mScissorL] = 0;
				motor[mScissorR] = 127;
			} else if (scissorLeftHeight < scissorRightHeight - potScissorErrorAllowance) {
				motor[mScissorL] = 127;
				motor[mScissorR] = 0;
			} else {
				motor[mScissorL] = motor[mScissorR] = 127;
			}
		} else if (vexRT[Btn5D]) {
			if (scissorLeftHeight + potScissorErrorAllowance < scissorRightHeight) {
				motor[mScissorL] = 0;
				motor[mScissorR] = -127;
			} else if (scissorLeftHeight > scissorRightHeight + potScissorErrorAllowance) {
				motor[mScissorL] = -127;
				motor[mScissorR] = 0;
			} else {
				motor[mScissorL] = motor[mScissorR] = -127;
			}
		} else {
			motor[mScissorL] = motor[mScissorR] = 0;
		}
		EndTimeSlice();
	}
}

bool clawOpen = true;
bool autoStacking = false;
task autoStack {
	if (autoStacking) {
		return;
	}

	autoStacking = true;

	motor[mClaw] = 127;
	wait1Msec (400);
	motor[mClaw] = 60;
	motor[mClawExtend] = 127;
	while (SensorValue[lfClaw] > 3000) {
		wait1Msec (10);
		if (vexRT[Btn8L]) {
			return;
		}
		//EndTimeSlice();
	}
	
	wait1Msec (10);
	//motor[mClaw] = -127;
	motor[mClawExtend] = -25;
	wait1Msec (1000);
	motor[mClaw] = -127;
	wait1Msec (300);
	motor[mClaw] = 0;
	clawOpen = true;
	wait1Msec (5000);
	motor[mClawExtend] = -127;
	wait1Msec (200);
	motor[mClawExtend] = 0;
	autoStacking = false;

	//while (abs(SensorValue[potScissor] - potPositions[stackedCount]) > potScissorErrorAllowance) {
		//motor[mScissorL] = mScissorValues[SensorValue[potScissor] < potPositions[stackedCount]];
	//}
}

task toggleClaw {
	while (true) {
		if (vexRT[Btn6U]) {
			while (vexRT[Btn6U]) { }
			if (clawOpen) {
				motor[mClaw] = 127;
				wait1Msec (250);
				motor[mClaw] = 30;
			} else {
				motor[mClaw] = -127;
				wait1Msec (400);
			}
			clawOpen = !clawOpen;
		}
		motor[mClaw] = (clawOpen ? 0 : 30);
		EndTimeSlice ();
	}
}

task main()
{
	//startTask(manualCtrl);
	//startTask(trayCtrl);
	//startTask (scissorLiftControl);
	
	
	startTask (autoStack);
	//startTask (toggleClaw);

	float theta = 90, power = 0, x = 0, y = 0, z = 0, direction = 1;
	int motorL1, motorL2, motorR1, motorR2;

	while (true) {

		// Update Sensor Values
		if (SensorValue[potScissorL] - 1100 < 1000) {
			scissorLeftHeight = SensorValue[potScissorL] - 1100;
		}
		if (2790 - SensorValue[potScissorR] < 1000) {
			scissorRightHeight = 2700 - SensorValue[potScissorR];
		}

		if (scissorRightHeight > 1200) {
			break;
		}

		x = vexRT[Ch4];
		y = vexRT[Ch3];
		z = vexRT[Ch1];
		power = sqrt(x * x + y * y);

		if (power > 10) {
			//if (y > 0) {
			if (power > 100) {
				power = 127;
			}
			direction = (y < 0 ? -1 : 1);
			motorL1 = motorL2 = (y - x) / 2;
			if (x > -20 && x < 20) {
				motorL1 = motorR1 = motorL2 = motorR2 = direction * power;
			} else if (y > -15 && y < 15) {
				if (y < 0) {
					motorL1 = motorL2 = 0;
					motorR1 = motorR2 = x;
				} else {
					motorL1 = motorL2 = x;
					motorR1 = motorR2 = 0;
				}
			} else {
				if (x < 0) {
					motorL2 = 0;
					motorR2 = direction * -x * (power / 127.0);
					motorL1 = motorR1 = (1.2 * y) / 2;
				} else {
					motorL2 = direction * x * (power / 127.0);
					motorR2 = 0;
					motorL1 = motorR1 = (1.2 * y) / 2;
				}
			}
		} else {
			motorL1 = motorL2 = motorR1 = motorR2 = 0;
		}

		if (abs(z) > 10) {
			motorL1 += (z * TURNING_COEFFICIENT);
			motorL2 += (z * TURNING_COEFFICIENT);
			motorR1 -= (z * TURNING_COEFFICIENT);
			motorR2 -= (z * TURNING_COEFFICIENT);
		}

		motor[mL1] = motorL1;
		motor[mL2] = motorL2;
		motor[mR1] = motorR1;
		motor[mR2] = motorR2;


		if (vexRT[Btn8D]) {
			startTask (autoStack);
		}
		

 		EndTimeSlice();
	}

}
