#pragma config(Sensor, in1,    potGoalLift,    sensorPotentiometer)
#pragma config(Sensor, in2,    ejctPot,        sensorPotentiometer)
#pragma config(Sensor, in3,    potScissorL,    sensorPotentiometer)
#pragma config(Sensor, in4,    potScissorR,    sensorPotentiometer)
#pragma config(Sensor, dgtl1,  ledR,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl2,  ledG,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl3,  legB,           sensorLEDtoVCC)
#pragma config(Motor,  port1,           mEject,        tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           mL1,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           mL2,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           mR1,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           mScissorL,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           sClaw,         tmotorServoStandard, openLoop)
#pragma config(Motor,  port7,           mClawExtend,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           mScissorR,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           mTray,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          mR2,           tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define potScissorErrorAllowance 100

int max (int a, int b) {
	return (a > b ?  a : b);
}

/*
Eject Pot Rest: 2200
Eject Pot Ejected: 1400
Eject Motor Eject: (-)
*/
int ejectRest = 2200;
int ejectOut = 1000;
int activationDelay = 1000;

int stackedCount = 0;
//int potPositions[12] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
//int mScissorValues[2] = {127, -127};


int scissorLeftHeight = 0, scissorRightHeight = 0;

task trayCtrl {
	while(true){
		if(vexRT[Btn7U]){
			motor[mEject] = -100;
			while(SensorValue(ejctPot) >= ejectOut){
				wait1Msec(1);
			}
			motor[mEject] = 100;
			while(SensorValue(ejctPot) <= ejectRest){
				wait1Msec(1);
			}
			motor[mEject] = 0;
		}

	}
}

task manualCtrl {
	while(true){
		if(vexRT[Btn8L]){
			motor[sClaw] = 127;
		}
		if(vexRT[Btn8R]){
			motor[sClaw] = -127;
		}
		if(vexRT[Btn6D]){
			motor[mTray] = 100;
		}else if(vexRT[Btn6U]){
			motor[mTray] = -100;
		} else{
			motor[mTray] = 0;
		}
		EndTimeSlice();
	}
}

task scissorLiftControl {
	while (true) {
		if (vexRT[Btn5U]) {
			if (scissorLeftHeight - potScissorErrorAllowance > scissorRightHeight) {
				motor[mScissorL] = 0;
				motor[mScissorR] = 127;
			} else if (scissorLeftHeight < scissorRightHeight - potScissorErrorAllowance) {
				motor[mScissorL] = 127;
				motor[mScissorR] = 0;
			} else {
				motor[mScissorL] = motor[mScissorR] = 127;
			}
		} else if (vexRT[Btn5D]) {
			if (scissorLeftHeight + potScissorErrorAllowance < scissorRightHeight) {
				motor[mScissorL] = 0;
				motor[mScissorR] = -127;
			} else if (scissorLeftHeight > scissorRightHeight + potScissorErrorAllowance) {
				motor[mScissorL] = -127;
				motor[mScissorR] = 0;
			} else {
				motor[mScissorL] = motor[mScissorR] = -127;
			}
		} else {
			motor[mScissorL] = motor[mScissorR] = 0;
		}
		EndTimeSlice();
	}
}

bool autoStacking = false;
task autoStack {
	if (autoStacking) {
		return;
	}
	//while (abs(SensorValue[potScissor] - potPositions[stackedCount]) > potScissorErrorAllowance) {
		//motor[mScissorL] = mScissorValues[SensorValue[potScissor] < potPositions[stackedCount]];
	//}
}


task main()
{
	//startTask(manualCtrl);
	//startTask(trayCtrl);
	startTask (scissorLiftControl);
	int value = 0;


	float theta = 90, power = 0, x = 0, y = 0, z = 0, vmL1, vmL2, vmR1, vmR2, vmax, direction = 1;

	while (true) {

		// Update Sensor Values
		if (SensorValue[potScissorL] - 1100 < 1000) {
			scissorLeftHeight = SensorValue[potScissorL] - 1100;
		}
		if (2790 - SensorValue[potScissorR] < 1000) {
			scissorRightHeight = 2700 - SensorValue[potScissorR];
		}

		if (scissorRightHeight > 1200) {
			break;
		}

		x = vexRT[Ch4];
		y = vexRT[Ch3];
		z = vexRT[Ch1];
		power = sqrt(x * x + y * y);


		if (power > 1000) {
			//if (y > 0) {
			if (power > 100) {
				power = 127;
			}
			direction = (y < 0 ? -1 : 1);
			motor[mL1] = motor[mL2] = (y - x) / 2;
			if (x > -20 && x < 20) {
				motor[mL1] = motor[mR1] = motor[mL2] = motor[mR2] = direction * power;
			} else if (y > -15 && y < 15) {
				if (y < 0) {
					motor[mL1] = motor[mL2] = 0;
					motor[mR1] = motor[mR2] = x;
				} else {
					motor[mL1] = motor[mL2] = x;
					motor[mR1] = motor[mR2] = 0;
				}
			} else {
				if (x < 0) {
					motor[mL2] = 0;
					motor[mR2] = direction * -x * (power / 127.0);
					motor[mL1] = motor[mR1] = (1.2 * y) / 2;
				} else {
					motor[mL2] = direction * x * (power / 127.0);
					motor[mR2] = 0;
					motor[mL1] = motor[mR1] = (1.2 * y) / 2;
				}
			}
		} else {
			motor[mL1] = motor[mL2] = motor[mR1] = motor[mR2] = 0;
		}

		if (abs(z) > 10) {
			motor[mL1] += z;
			motor[mL2] += z;
			motor[mR1] -= z;
			motor[mR2] -= z;
		}

		motor[mR2] = 127;

		//value = (vexRT[Btn5D] ? mScissorValues[0] : (vexRT[Btn5U] ? mScissorValues[1] : 0));

/*
		if (vexRT[Btn7D]) {
			motor[mTray] = 100;
		} else if(vexRT[Btn7U]) {
			motor[mTray] = -100;
		} else {
			motor[mTray] = 0;
		}
		*/

 		EndTimeSlice();
	}

}
