#pragma config(Sensor, in1,    potGoalLift,    sensorPotentiometer)
#pragma config(Sensor, in2,    ejctPot,        sensorPotentiometer)
#pragma config(Sensor, in3,    potScissorL,    sensorPotentiometer)
#pragma config(Sensor, in4,    potScissorR,    sensorPotentiometer)
#pragma config(Sensor, in5,    lfClaw,         sensorLineFollower)
#pragma config(Sensor, dgtl1,  ledR,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl2,  ledG,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl3,  legB,           sensorLEDtoVCC)
#pragma config(Motor,  port1,           mEject,        tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           mL1,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           mL2,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           mR1,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           mScissorL,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           mClaw,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           mClawExtend,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           mScissorR,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           mTray,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          mR2,           tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define potScissorErrorAllowance 100

int max (int a, int b) {
	return (a > b ?  a : b);
}
long map(long x, long in_min, long in_max, long out_min, long out_max) //maps values in given ranges linearly.
{
	return (x - in_min) * (out_max - out_min) / (in_max - in_min) + out_min;
}

/*
Eject Pot Rest: 2200
Eject Pot Ejected: 1400
Eject Motor Eject: (-)
*/
int ejectRest = 2200;
int ejectOut = 1000;
int activationDelay = 1000;

int stackedCount = 0;
//int potPositions[12] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
//int mScissorValues[2] = {127, -127};


int scissorLeftHeight = 0, scissorRightHeight = 0;

task trayCtrl {
	while(true){
		if(vexRT[Btn7U]){
			motor[mEject] = -100;
			while(SensorValue(ejctPot) >= ejectOut){
				wait1Msec(1);
			}
			motor[mEject] = 100;
			while(SensorValue(ejctPot) <= ejectRest){
				wait1Msec(1);
			}
			motor[mEject] = 0;
		}

	}
}

task manualCtrl {
	while(true){
		/*
		if(vexRT[Btn8L]){
		motor[mClaw] = 127;
		}
		if(vexRT[Btn8R]){
		motor[sClaw] = -127;
		}
		*/
		if(vexRT[Btn6D]){
			motor[mTray] = 100;
			}else if(vexRT[Btn6U]){
			motor[mTray] = -100;
			} else{
			motor[mTray] = 0;
		}
		EndTimeSlice();
	}
}

task scissorLiftControl {
	while (true) {
		if (vexRT[Btn5U]) {

			//Hey david we realigned the potentiometers. They read similar values for similar positions in the scissor lift. I only did this because Joshua accidently messed up the alignment.

			int ScisLeft = potScissorL;  //ensure potentiometer values are constant while calculating motor difference
			int ScisRight = potScissorR;

			int diff= abs(potScissorL-potScissorR); //get difference for future calculations

			if(diff>potScissorErrorAllowance){ 											//dothe scissor lifts have too much difference?
				if(ScisLeft > ScisRight){															//is the left motor faster?
					motor[mScissorL] = 127 - map(diff,100,500,32,96); //slow faster motor proportionally to the difference between the two sides.
					} else{																							//handle other scissor lift
					motor[mScissorR] = 127 - map(diff,100,500,32,96); //slow motor
				}
				} else{
				motor[mScissorL]=motor[mScissorR]=127; 						//default motor speed if button pressed
			}
		} else if (vexRT[Btn5D]) {
		int ScisLeft = potScissorL;  //ensure potentiometer values are constant while calculating motor difference
		int ScisRight = potScissorR;

		int diff= abs(potScissorL-potScissorR); //get the difference for future calculations

		if(diff>potScissorErrorAllowance){ 											//do the scissor lifts have too much difference?
			if(ScisLeft < ScisRight){															//is the left motor faster?
				motor[mScissorL] = -127 + map(diff,100,500,32,96);	//slow faster motor proportionally to the difference between the two sides.
				} else{																								//handle other scissor lift being faster
				motor[mScissorR] = -127 + map(diff,100,500,32,96);	//slow apropriate motor
			}
			} else{
				motor[mScissorL]=motor[mScissorR]=-127; //default motor speed if button pressed
			}
		} else {
			motor[mScissorL] = motor[mScissorR] = 0;
		}
		EndTimeSlice();
	}
}

bool autoStacking = false;
task autoStack {
	if (!autoStacking) {
		startTask(manualStack)
		stopTask(autoStack);
	}

	motor[mClaw] = 50;
	wait1Msec(1000);
	motor[mClawExtend] = 127;
	while (SensorValue[lfClaw] > 2970) {
		wait1Msec(1);
		//EndTimeSlice();
	}
	wait1Msec(200);
	motor[mClawExtend] = 0;
	motor[mClaw] = 127;
	wait1Msec(1000);
	motor[mClawExtend] = -127;
	motor[mClaw] = motor[mClawExtend] = 0;
	//while (abs(SensorValue[potScissor] - potPositions[stackedCount]) > potScissorErrorAllowance) {
	//motor[mScissorL] = mScissorValues[SensorValue[potScissor] < potPositions[stackedCount]];
	//}
}
task manualStack{
	while(true){

	}
}


task main()
{
	//startTask(manualCtrl);
	//startTask(trayCtrl);
	//startTask (scissorLiftControl);
	startTask (autoStack);
	int value = 0;


	float theta = 90, power = 0, x = 0, y = 0, z = 0, vmL1, vm5L2, vmR1, vmR2, vmax, direction = 1;
	int motorL1, motorL2, motorR1, motorR2;

	while (true) {

		// Update Sensor Values
		if (SensorValue[potScissorL] - 1100 < 1000) {
			scissorLeftHeight = SensorValue[potScissorL] - 1100;
		}
		if (2790 - SensorValue[potScissorR] < 1000) {
			scissorRightHeight = 2700 - SensorValue[potScissorR];
		}

		if (scissorRightHeight > 1200) {
			break;
		}

		x = vexRT[Ch4];
		y = vexRT[Ch3];
		z = vexRT[Ch1];
		power = sqrt(x * x + y * y);


		if (power > 10) {
			//if (y > 0) {
			if (power > 100) {
				power = 127;
			}
			direction = (y < 0 ? -1 : 1);
			motorL1 = motorL2 = (y - x) / 2;
			if (x > -20 && x < 20) {
				motorL1 = motorR1 = motorL2 = motorR2 = direction * power;
				} else if (y > -15 && y < 15) {
				if (y < 0) {
					motorL1 = motorL2 = 0;
					motorR1 = motorR2 = x;
					} else {
					motorL1 = motorL2 = x;
					motorR1 = motorR2 = 0;
				}
				} else {
				if (x < 0) {
					motorL2 = 0;
					motorR2 = direction * -x * (power / 127.0);
					motorL1 = motorR1 = (1.2 * y) / 2;
					} else {
					motorL2 = direction * x * (power / 127.0);
					motorR2 = 0;
					motorL1 = motorR1 = (1.2 * y) / 2;
				}
			}
			} else {
			motorL1 = motorL2 = motorR1 = motorR2 = 0;
		}

		if (abs(z) > 10) {
			motorL1 += z;
			motorL2 += z;
			motorR1 -= z;
			motorR2 -= z;
		}

		motorL1 = (motorL1 > 127 ? 127 : motorL1);
		motorL2 = (motorL2 > 127 ? 127 : motorL2);
		motorR1 = (motorR1 > 127 ? 127 : motorR1);
		motorR2 = (motorR2 > 127 ? 127 : motorR2);


		motor[mL1] = motorL1;
		motor[mL2] = motorL2;
		motor[mR1] = motorR1;
		motor[mR2] = motorR2;

		//value = (vexRT[Btn5D] ? mScissorValues[0] : (vexRT[Btn5U] ? mScissorValues[1] : 0));

		/*
		if (vexRT[Btn7D]) {
		motor[mTray] = 100;
		} else if(vexRT[Btn7U]) {
		motor[mTray] = -100;
		} else {
		motor[mTray] = 0;
		}
		*/

		EndTimeSlice();
	}

}
